### ISSUE TITLE
Problems with migrations

### ISSUE THREAD

**Issue by InverMN** [YgorCastor/ravix-ecto#2]
Hello again!

When I try to run the `mix test` command, I get that error:

```
12:44:24.198 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
  migrationsns, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run mix   ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :ravix_test, RavixTest.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (UndefinedFunctionError) function Ravix.Ecto.Adapter.execute_ddl/3 is undefined or private. Did you mean:

      * execute/5

    (ravix_ecto 0.2.1) Ravix.Ecto.Adapter.execute_ddl(%{adapter: Ravix.Ecto.Adapter, cache: #Reference<0.1501241443.1897267202.25822>, pid: #PID<0.381.0>, repo: RavixTest.Repo}, {:create_if_not_exists, %Ecto.Migration.Table{comment: nil, engine: nil, name: :schema_migrations, options: nil, prefix: nil, primary_key: true}, [{:add, :version, :bigint, [primary_key: true]}, {:add, :inserted_at, :naive_datetime, []}]}, [timeout: :infinity, log: false, schema_migration: true])
    (ecto_sql 3.8.0) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.8.0) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.8.0) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
    (ecto_sql 3.8.0) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    (ecto_sql 3.8.0) lib/mix/tasks/ecto.migrate.ex:141: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.8.0) lib/mix/tasks/ecto.migrate.ex:129: Mix.Tasks.Ecto.Migrate.run/2
```

Once again I would like to ask for help

**Comment by ycastorium** [comment]
Hey! Yep, migrations are not implemented for Raven, please check this repo: https://github.com/YgorCastor/phoenix-ravix-sample.

You can solve this in two ways: 

If you are using two repos, one relational and ravendb as secondary you can just remove the EctoRepos configuration of phoenix: 

```elixir
config :phoenix_ravix_example,
  ecto_repos: [PhoenixRavixExample.Repo, PhoenixRavixExample.RavenRepo ## DON'T]
```

If you are using only the Ravix-Ecto repo, you need to disable the repo migration check at the endpoints.ex file 

```elixir
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :phoenix_ravix_example <<<<< Remove this one
  end
```
  
  And remove the ecto.migrate from your mix.exs run: 
  
```elixir
    [
      setup: ["deps.get", "ecto.setup"],
      "ecto.setup": ["ecto.create", "ecto.migrate" <<<< This one, "run priv/repo/seeds.exs" <<<< This one],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      test: ["ecto.create --quiet", "ecto.migrate --quiet" <<<< This one, "test"],
      "assets.deploy": ["esbuild default --minify", "phx.digest"]
    ]
```
 
  Remember that the Ravix-Ecto is not SQL, so que SQL sandbox will not work with it. Just check the repo i linked up above for a working config.
